spring:
  application:
    name: @project.artifactId@
  kafka:
    topic: test
    bootstrap-servers: http://localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: "test-group"
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: mydb
      username: root
      password: secret
